// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
module.exports = function(app, server){
    const basepath = '/api';
    require('./swagger')(app);
    require('./pets')(app, basepath);
    require('./public')(app);
    require('./health')(app);
};
